name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install pytest
    - run: pytest

  EOF-CRLF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check CRLF
        uses: erclu/check-crlf@v1
      - name: Check EOF
        uses: fernandrone/linelint@0.0.6